### ISSUE TITLE
Type error in ex2-1.html

### ISSUE THREAD

**Issue by fripSide** [fem-d/webGL#1]
In chapter2, listing ex2-1.html, line 48:
vertexPosition = gl.getAttribLocation(prg, "aVertexPostion");
the aVertexPostion should be "aVertexPosition" P-O-S-I-T-I-O-N postion.
Otherwise, it will produce an error:
WebGL: INVALID_VALUE: enableVertexAttribArray: index out of range

**Comment by haohao667788** [comment]
fixed, 3x
